{
 "title": "Production JWT Pizza",
 "description": "1",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pizza Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "changes(pizzaPurchases{result=\"failure\"}[1m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Pizza Sales",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "changes(pizzaPurchases{result=\"success\"}[1m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Authorization Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(authAttempts{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "changes(pizzaRevenue_BTC{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Bitcoin"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "activeUsers_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Endpoint Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(__name__) (changes(endpointLatency_milliseconds{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "Change in Latency"
    }
   ]
  },
  {
   "title": "Pizza Sale Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "changes(pizzaLatency_milliseconds{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Change in Pizza Sale Latency"
    }
   ]
  },
  {
   "title": "HTTP Requests Method/Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(requestsByMethod{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum(rate(requestsByMethod{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU usage ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memoryUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}